import { useState, useEffect } from 'react'
import NavBar from '../NavBar/NavBar';
import './Progress.css';

// The four stat cards at the top
type progressStats = {
    workouts: number;
    avgCalories: number;
    strengthTrend: string; // e.g. "+6.8%"
    bodyWeight: number;    // lb
}

// Feedback options the user can pick after a workout
const feedbackOptions = ['Great', 'Too easy', 'Too hard', 'Too long'];

// Size of the drawing area for the line chart (the SVG scales to fit its box)
const chartWidth = 660;
const chartHeight = 280;

export default function Progress(){
    //These values will come from the backend later
    const [stats, setStats] = useState<progressStats>({ workouts: 0, avgCalories: 0, strengthTrend: '', bodyWeight: 0 });
    const [weightHistory, setWeightHistory] = useState<number[]>([]);
    const [aiInsight, setAiInsight] = useState('');
    // Which feedback button is selected
    const [selectedFeedback, setSelectedFeedback] = useState('Great');

    // Fills the stat cards (hardcoded until the backend is connected)
    const getProgressStats = () => {
        setStats({ workouts: 12, avgCalories: 2450, strengthTrend: '+6.8%', bodyWeight: 154 });
    }

    // Weight for each of the last 6 weeks (oldest first)
    const getWeightHistory = () => {
        setWeightHistory([158, 156.9, 156.2, 155.2, 154.8, 154]);
    }

    // Text shown under the chart (will be generated by the AI later)
    const getAiInsight = () => {
        setAiInsight('AI insight: weight is trending gradually while workout consistency is improving.');
    }

    // Saves which feedback button was clicked (send to the backend later)
    const handleFeedbackClick = (feedback: string) => {
        setSelectedFeedback(feedback);
    }

    // Load all the data once when the page first renders
    useEffect(() => {
        getProgressStats();
        getWeightHistory();
        getAiInsight();
    }, []);

    // Turn the weights into x/y positions for the chart
    // Highest weight sits on the top grid line, lowest on the bottom one
    const maxWeight = Math.max(...weightHistory);
    const minWeight = Math.min(...weightHistory);
    const chartPoints = weightHistory.map((weight, index) => {
        const x = 51 + index * (549 / Math.max(weightHistory.length - 1, 1));
        const y = 70 + ((maxWeight - weight) / (maxWeight - minWeight || 1)) * 140;
        return { x, y };
    });
    // "x,y x,y x,y" string used by the <polyline>
    const linePoints = chartPoints.map((p) => `${p.x},${p.y}`).join(' ');

    // The four cards shown at the top (label + formatted value)
    const statCards = [
        { label: 'Workouts', value: `${stats.workouts}` },
        { label: 'Avg calories', value: stats.avgCalories.toLocaleString() },
        { label: 'Strength trend', value: stats.strengthTrend },
        { label: 'Body weight', value: `${stats.bodyWeight} lb` },
    ];

    return (
        <div className='progress-page'>
            <NavBar />
            <main className='progress-main'>
                <h1 className='page-title'>Progress &amp; Insights</h1>
                <p className='page-subtitle'>Track your results and help the AI refine future plans.</p>

                {/* Four stat cards */}
                <div className='stats-row'>
                    {statCards.map((card) => (
                        <div className='stat-card' key={card.label}>
                            <span className='stat-label'>{card.label}</span>
                            <span className='stat-value'>{card.value}</span>
                        </div>
                    ))}
                </div>

                <div className='progress-grid'>
                    {/* Weight trend card with line chart */}
                    <div className='weight-trend card'>
                        <h2>Weight Trend</h2>
                        <p className='card-subtitle'>Last 6 weeks</p>
                        <div className='chart-box'>
                            <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`}>
                                {/* three horizontal grid lines */}
                                <line x1='20' y1='70' x2='640' y2='70' className='grid-line' />
                                <line x1='20' y1='140' x2='640' y2='140' className='grid-line' />
                                <line x1='20' y1='210' x2='640' y2='210' className='grid-line' />
                                {/* the weight line */}
                                <polyline points={linePoints} className='chart-line' />
                                {/* a dot for each week */}
                                {chartPoints.map((p, index) => (
                                    <circle key={index} cx={p.x} cy={p.y} r='6' className='chart-dot' />
                                ))}
                            </svg>
                        </div>
                        <p className='ai-insight'>{aiInsight}</p>
                    </div>

                    {/* Workout feedback card */}
                    <div className='workout-feedback card'>
                        <h2>Workout Feedback</h2>
                        <p className='card-subtitle'>How did today's workout feel?</p>
                        {feedbackOptions.map((option) => (
                            <button
                                key={option}
                                className={option === selectedFeedback ? 'feedback-button active' : 'feedback-button'}
                                onClick={() => handleFeedbackClick(option)}
                            >
                                {option}
                            </button>
                        ))}
                        <p className='feedback-note'>FitStack can use your feedback to adjust exercise selection, volume, and future workouts.</p>
                    </div>
                </div>
            </main>
        </div>
    );
}
