"""initial tables

Revision ID: 5e27e302a162
Revises: 
Create Date: 2026-09-30 18:28:05.479597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5e27e302a162'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_prescriptions',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('sets_min', sa.Integer(), nullable=False),
    sa.Column('sets_max', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=False),
    sa.Column('reps_max', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_rpe_min', sa.Float(), nullable=False),
    sa.Column('target_rpe_max', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('exercises',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('force_type', sa.String(), nullable=False),
    sa.Column('mechanics', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('primary_muscles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('secondary_muscles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('tertiary_muscles', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('equipment_required', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('exercise_family', sa.String(), nullable=False),
    sa.Column('movement_pattern', sa.String(), nullable=False),
    sa.Column('training_role', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('unilateral', sa.Boolean(), nullable=False),
    sa.Column('load_type', sa.String(), nullable=False),
    sa.Column('progression_methods', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('substitution_group', sa.String(), nullable=True),
    sa.Column('goal_suitability', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('mobility_requirements', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('balance_requirement', sa.String(), nullable=False),
    sa.Column('stability_requirement', sa.String(), nullable=False),
    sa.Column('fatigue_cost', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('available_equipment', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('preferred_exercises', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('disliked_exercises', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('limitations', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('exercise_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('workout_plan_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('sets_planned', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=False),
    sa.Column('reps_max', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('starting_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plans',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('workout_programs',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('workout_sets',
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('workout_programs')
    op.drop_table('workout_plans')
    op.drop_table('workout_plan_exercises')
    op.drop_table('workout_feedback')
    op.drop_table('profiles')
    op.drop_table('exercises')
    op.drop_table('exercise_prescriptions')
    # ### end Alembic commands ###
