"""update exercise table

Revision ID: 841347ef3c05
Revises: fac2a66b86d7
Create Date: 2026-10-06 20:45:18.424810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '841347ef3c05'
down_revision: Union[str, Sequence[str], None] = 'fac2a66b86d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'source')
    op.drop_column('exercises', 'source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
