"""update workout models

Revision ID: fac2a66b86d7
Revises: d93eafc1e10a
Create Date: 2026-10-04 10:07:30.261423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac2a66b86d7'
down_revision: Union[str, Sequence[str], None] = 'd93eafc1e10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_availability',
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('availability_id'),
    sa.UniqueConstraint('user_id', 'day_of_week', name='uq_user_availability_day')
    )
    op.create_unique_constraint('uq_exercise_prescription_goal', 'exercise_prescriptions', ['exercise_id', 'goal'])
    op.create_foreign_key(None, 'exercise_prescriptions', 'exercises', ['exercise_id'], ['exercise_id'], ondelete='CASCADE')
    op.add_column('exercises', sa.Column('searchable_text', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('source', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('source_id', sa.String(), nullable=True))
    op.alter_column('exercises', 'exercise_family',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'movement_pattern',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'training_role',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('exercises', 'unilateral',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('exercises', 'load_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'progression_methods',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('exercises', 'goal_suitability',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('exercises', 'mobility_requirements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('exercises', 'balance_requirement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'stability_requirement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercises', 'fatigue_cost',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('profiles', 'days_per_week')
    op.drop_column('profiles', 'session_duration_minutes')
    op.create_unique_constraint(None, 'workout_feedback', ['workout_id'])
    op.create_foreign_key(None, 'workout_feedback', 'workout_plans', ['workout_id'], ['workout_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workout_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('workout_plan_exercises', sa.Column('target_rpe_min', sa.Float(), nullable=True))
    op.add_column('workout_plan_exercises', sa.Column('target_rpe_max', sa.Float(), nullable=True))
    op.add_column('workout_plan_exercises', sa.Column('planned_weight', sa.Float(), nullable=True))
    op.add_column('workout_plan_exercises', sa.Column('weight_unit', sa.String(length=2), nullable=False))
    op.add_column('workout_plan_exercises', sa.Column('progression_method', sa.String(), nullable=True))
    op.create_unique_constraint('uq_workout_exercise_order', 'workout_plan_exercises', ['workout_id', 'exercise_order'])
    op.create_foreign_key(None, 'workout_plan_exercises', 'workout_plans', ['workout_id'], ['workout_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workout_plan_exercises', 'exercises', ['exercise_id'], ['exercise_id'])
    op.drop_column('workout_plan_exercises', 'starting_weight')
    op.drop_column('workout_plan_exercises', 'target_rpe')
    op.create_unique_constraint('uq_program_week_day', 'workout_plans', ['program_id', 'week_number', 'day_of_week'])
    op.create_foreign_key(None, 'workout_plans', 'workout_programs', ['program_id'], ['program_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workout_programs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('workout_sets', sa.Column('workout_plan_exercise_id', sa.UUID(), nullable=False))
    op.add_column('workout_sets', sa.Column('weight_unit', sa.String(length=2), nullable=False))
    op.create_foreign_key(None, 'workout_sets', 'workout_plan_exercises', ['workout_plan_exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_sets', 'exercise_id')
    op.drop_column('workout_sets', 'workout_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('workout_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('workout_sets', sa.Column('exercise_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.drop_column('workout_sets', 'weight_unit')
    op.drop_column('workout_sets', 'workout_plan_exercise_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_programs', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.drop_constraint('uq_program_week_day', 'workout_plans', type_='unique')
    op.add_column('workout_plan_exercises', sa.Column('target_rpe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('workout_plan_exercises', sa.Column('starting_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_plan_exercises', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_plan_exercises', type_='foreignkey')
    op.drop_constraint('uq_workout_exercise_order', 'workout_plan_exercises', type_='unique')
    op.drop_column('workout_plan_exercises', 'progression_method')
    op.drop_column('workout_plan_exercises', 'weight_unit')
    op.drop_column('workout_plan_exercises', 'planned_weight')
    op.drop_column('workout_plan_exercises', 'target_rpe_max')
    op.drop_column('workout_plan_exercises', 'target_rpe_min')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_feedback', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_feedback', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workout_feedback', type_='unique')
    op.add_column('profiles', sa.Column('session_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('profiles', sa.Column('days_per_week', sa.INTEGER(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.alter_column('exercises', 'fatigue_cost',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'stability_requirement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'balance_requirement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'mobility_requirements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('exercises', 'goal_suitability',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('exercises', 'progression_methods',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('exercises', 'load_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'unilateral',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('exercises', 'training_role',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('exercises', 'movement_pattern',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'exercise_family',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exercises', 'source_id')
    op.drop_column('exercises', 'source')
    op.drop_column('exercises', 'embedding_model')
    op.drop_column('exercises', 'searchable_text')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'exercise_prescriptions', type_='foreignkey')
    op.drop_constraint('uq_exercise_prescription_goal', 'exercise_prescriptions', type_='unique')
    op.drop_table('user_availability')
    # ### end Alembic commands ###
